name: Build SPFx Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
        working-directory: training-video-player

      - name: Bundle solution
        run: npx gulp bundle --ship
        working-directory: training-video-player

      - name: Package solution
        run: npx gulp package-solution --ship
        working-directory: training-video-player

      - name: Upload SPFx package
        uses: actions/upload-artifact@v4
        with:
          name: spfx-sppkg
          path: training-video-player/sharepoint/solution/*.sppkg
